title: lastalios
author: lastalios
author.email: lastalios@gmail.com
url: https://lastalios.github.io/

github: lastalios
twitter: lastalios
gaid:

permalink: /blog/:title
pygments: true
markdown: rdiscount
rdiscount:
  extensions: [smart]
